name = "film-album-api"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[vars]
# 图床配置
IMG_BED_URL = "https://img.072199.xyz"
# NOTE: 密钥类变量请通过 npx wrangler secret put 指令设置，不要存在此处

[[d1_databases]]
binding = "DB"
database_name = "film-album-db"
database_id = "7bbb2117-9bc6-4d84-865e-6df3633453d5"
